<?php

Yii::import('zii.widgets.CMenu');

class Menu extends CMenu {

  /**
   * Renders the content of a menu item.
   * Note that the container and the sub-menus are not rendered here.
   * @param array $item the menu item to be rendered. Please see {@link items} on what data might be in the item.
   * @return string
   * @since 1.1.6
   */
  protected function renderMenuItem($item)
  {
    if ($item['active'] && $this->activeCssClass != '') {
      $item['linkOptions']['class'].=' '.$this->activeCssClass;
    }
    if(isset($item['url']))
    {
      $linkLabelWrapper = array_key_exists('linkLabelWrapper', $item) ? $item['linkLabelWrapper'] : $this->linkLabelWrapper;
      $label=$linkLabelWrapper===null ? $item['label'] : '<'.$linkLabelWrapper.'>'.$item['label'].'</'.$linkLabelWrapper.'>';
      return CHtml::link($label,$item['url'],isset($item['linkOptions']) ? $item['linkOptions'] : array());
    }
    else
      return CHtml::tag('span',isset($item['linkOptions']) ? $item['linkOptions'] : array(), $item['label']);
  }

  /**
   * Checks whether a menu item is active.
   * This is done by checking if the currently requested URL is generated by the 'url' option
   * of the menu item. Note that the GET parameters not specified in the 'url' option will be ignored.
   * @param array $item the menu item to be checked
   * @param string $route the route of the current request
   * @return boolean whether the menu item is active
   */
  protected function isItemActive($item,$route)
  {
    if ($item['url']['0'] === 'admin') {
      $match = !strcasecmp(trim($item['url'][0],'/').'/dashboard/index', $route);
    } else {
      if ($item['url'][0][0] === '/') {
        $match = strpos($route, trim($item['url'][0],'/')) !== false;
      } else {
        $match = !strcasecmp(trim($item['url'][0],'/'), $route);
      }
    }

    if(isset($item['url']) && is_array($item['url']) && $match)
    {
      unset($item['url']['#']);
      if(count($item['url'])>1)
      {
        foreach(array_splice($item['url'],1) as $name=>$value)
        {
          if(!isset($_GET[$name]) || $_GET[$name]!=$value)
            return false;
        }
      }
      return true;
    }
    return false;
  }

}

?>